import type { DashboardState, MainPrediction, HealthShieldData, InventoryData, BinaryPrediction, SequenceData, MapData, StreamData, Alert, Recommendation, ModuleStatus } from './types'
const now = () => new Date().toISOString()
const meta = (source: string, status: ModuleStatus = 'ready') => ({ sessionId: 'demo-live-001', predictionId: 'pred-' + Date.now(), timestamp: now(), source, status, modelVersion: 'demo-v0.1' })
const icon = (color: string) => 'data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' width=\'96\' height=\'96\'%3E%3Crect width=\'96\' height=\'96\' rx=\'18\' fill=\'%230b1425\'/%3E%3Cpath d=\'M48 14L78 48 48 82 18 48Z\' fill=\'' + color + '\' fill-opacity=\'.85\' stroke=\'%23ffffff\' stroke-opacity=\'.55\' stroke-width=\'3\'/%3E%3C/svg%3E'
const frame = (index: number) => 'data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' viewBox=\'0 0 320 180\'%3E%3Cdefs%3E%3ClinearGradient id=\'g\' x1=\'0\' x2=\'1\' y1=\'0\' y2=\'1\'%3E%3Cstop stop-color=\'%230d3a68\'/%3E%3Cstop offset=\'.55\' stop-color=\'%231b285a\'/%3E%3Cstop offset=\'1\' stop-color=\'%23542a67\'/%3E%3C/linearGradient%3E%3C/defs%3E%3Crect width=\'320\' height=\'180\' fill=\'url(%23g)\'/%3E%3Cpath d=\'M0 145 55 100l50 34 55-69 60 45 100-56v126H0z\' fill=\'%2313263b\'/%3E%3Ccircle cx=\'' + (65 + index * 34) + '\' cy=\'' + (55 + index * 5) + '\' r=\'18\' fill=\'%23e9b949\' fill-opacity=\'.9\'/%3E%3Ctext x=\'14\' y=\'28\' fill=\'white\' font-family=\'Arial\' font-size=\'14\' font-weight=\'bold\'%3EFRAME ' + index + '%3C/text%3E%3C/svg%3E'
export function createDemoSnapshot(tick: number): Omit<DashboardState, 'sessionStatus' | 'connection' | 'sessionId' | 'soundEnabled' | 'lastUpdate'> {
  const health = Math.max(34, 82 - (tick % 9) * 2), shield = Math.min(100, 48 + (tick % 7) * 5), victory = 0.38 + (tick % 5) * 0.035, elimination = 0.44 - (tick % 4) * 0.02, eliminated = 1 - victory - elimination
  const common = meta('demo-engine')
  const mainPrediction: MainPrediction = { ...common, predictedClass: victory > elimination ? 'victory' : 'elimination', eliminatedProbability: eliminated, eliminationProbability: elimination, victoryProbability: victory, confidence: Math.max(victory, elimination, eliminated), latencyMs: 118 + (tick % 4) * 11 }
  const healthShield: HealthShieldData = { ...meta('health-shield-model'), health, shield, trend: [72, 70, 76, 73, health], winProbability: 0.61, lossProbability: 0.39 }
  const inventory: InventoryData = { ...meta('inventory-model'), winProbability: 0.68, lossProbability: 0.32, items: [{ id: '1', name: 'Rifle táctico', rarity: 'Épico', quantity: 1, ammo: 96, icon: icon('%23b14cff') }, { id: '2', name: 'Escopeta', rarity: 'Raro', quantity: 1, ammo: 18, icon: icon('%233d8dffff') }, { id: '3', name: 'Mini escudo', rarity: 'Poco común', quantity: 4, icon: icon('%2334d399ff') }, { id: '4', name: 'Botiquín', rarity: 'Poco común', quantity: 1, icon: icon('%2322c55eff') }, tick % 3 === 0 ? null : { id: '5', name: 'Rastreador', rarity: 'Legendario', quantity: 1, icon: icon('%23f59e0bff') }], recommendation: shield < 60 ? 'Conserva y usa los mini escudos antes del próximo enfrentamiento.' : 'Inventario equilibrado para mantener presión a media distancia.', historicalEvidence: ['Ejemplo histórico A', 'Ejemplo histórico B'] }
  const binary = (source: string, win: number): BinaryPrediction => ({ ...meta(source), winProbability: win, lossProbability: 1 - win })
  const sequence: SequenceData = { ...binary('sequence-model', 0.57), frames: Array.from({ length: 6 }, (_, i) => ({ id: 'frame-' + (i + 1), index: i + 1, timestamp: now(), status: i === 5 && tick % 3 === 0 ? 'processing' : 'ready', image: frame(i + 1) })) }
  const stream: StreamData = { ...meta('capture-gateway'), available: true, resolution: '1920 × 1080', fps: 60, message: 'Captura activa · señal estable' }
  const map: MapData = { ...binary('map-model', 0.54), image: frame((tick % 6) + 1) }
  const alerts: Alert[] = health < 45 ? [{ id: 'alert-' + tick, severity: 'critical', title: 'Vida baja', message: 'La vida está por debajo del nivel recomendado.', timestamp: now() }] : [{ id: 'alert-' + tick, severity: 'info', title: 'Señal sincronizada', message: 'Todas las modalidades reportaron una actualización.', timestamp: now() }]
  const recommendations: Recommendation[] = [{ id: 'r1', priority: health < 55 ? 'alta' : 'media', text: health < 55 ? 'Busca cobertura' : 'Mantén la cobertura', explanation: 'La recomendación combina vida, escudo y secuencia actual.', source: 'Modelo multimodal', timestamp: now(), validity: '45 s' }, { id: 'r2', priority: 'media', text: shield < 60 ? 'Recupera escudo' : 'Conserva recursos de curación', explanation: inventory.recommendation, source: 'Vida y escudo + inventario', timestamp: now(), validity: '30 s' }]
  return { stream, mainPrediction, healthShield, inventory, audio: binary('audio-model', 0.49), sequence, map, alerts, recommendations }
}
